services:
  expoapi-bridge:
    image: ghcr.io/teknikens-hus/expoapi-bridge:latest
    ports:
      - "8080:8080"
    environment:
      TOKEN: ${TOKEN}
      ENDPOINT: ${ENDPOINT}
      DAYS_FORWARD: "7"
      DAYS_BACKWARD: "0"
      CRON_SCHEDULE: "0 * * * *"
      TZ: "Europe/Stockholm"
    restart: unless-stopped