---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expoapi-bridge
  labels:
    app: expoapi-bridge
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: expoapi-bridge
  template:
    metadata:
      labels:
        app: expoapi-bridge
    spec:
      containers:
        - image: ghcr.io/teknikens-hus/expoapi-bridge:latest
          name: expoapi-bridge
          ports:
            - name: webserver
              containerPort: 8080
          env:
            # This needs to be created separately, see README.md
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: expoapi-bridge
                  namespace: expoapi-bridge
                  key: token
            # This needs to be created separately, see README.md
            - name: ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: expoapi-bridge
                  namespace: expoapi-bridge
                  key: endpoint
              # Fetch bookings 7 days forward
            - name: DAYS_FORWARD
              value: "7"
              # Default 0 days, only fetch today and forward
            - name: DAYS_BACKWARD
              value: "0"
              # Default to run every hour
            - name: CRON_SCHEDULE
              value: "0 * * * *"
              # Update to your timezone
            - name: TZ
              value: Europe/Stockholm
          # Adjust the resource limits as needed
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "200Mi"
            limits:
              memory: "256Mi"
              cpu: "200m"
              ephemeral-storage: "1Gi"
          # Make sure we run as non-root "app"
          securityContext:
            runAsUser: 1001
            runAsGroup: 2001
            fsGroup: 2001
